### ISSUE TITLE
Navigation to the Scala Library isn't working

### ISSUE THREAD

**Issue by ckipp01** [sourcegraph/scip-java#496]
If I do an upload for a Scala project, like you can see [here](https://sourcegraph.com/github.com/ckipp01/mill-giter8/-/code-graph/uploads/TFNJRlVwbG9hZDoyMDY5MDc3) that includes `maven/org.scala-lang/scala-library` under the dependencies section I would expect then that navigation to the Scala Library would work for my project. For example if you take this chunk of code here:

https://sourcegraph.com/github.com/ckipp01/mill-giter8/-/blob/plugin/src/io/kipp/mill/giter8/G8Module.scala?L67-72

I'd expect to be able to execute a goto definition on `get`, `map`, and `getOrElse`, but currently they don't work. After the latest release of `scip-java` indexing of the Scala Library seems to be working fine as you can see [here](https://sourcegraph.com/maven/org.scala-lang/scala-library/-/code-graph/uploads?visible=5). Is there something else needed for this to work, or is there internally something funky going on?

**Comment by Strum355** [comment]
This appears to be a problem with how we're indexing `org.scala-lang:scala-library`. When indexing scala files (specifically in "package repos" aka repos synthesized from JAR files pulled from maven central etc), we add `org.scala-lang:scala-library:3.13.6` to the classpath. This version is derived from the version used by `mtags` (see [here](https://sourcegraph.com/github.com/sourcegraph/scip-java@3725605c81a08d04a27c7939e818a091df35e93e/-/blob/scip-java/src/main/scala/com/sourcegraph/scip_java/buildtools/ScipBuildTool.scala?L391-L393)), with a hard-coded mtags version [here](https://sourcegraph.com/github.com/sourcegraph/scip-java@3725605c81a08d04a27c7939e818a091df35e93e/-/blob/build.sbt?L21). 

This has two effects:
1. All package repos will depend only on scala-library 2.13.6 
2. Indexing scala-library of any version will have both itself and scala-library 2.13.6 in the classpath, and the due to some selection process (dont know where), the latter is chosen

**Comment by Strum355** [comment]
mtags turned out to be a bit of a red herring. Whats actually happening is that [`ScalaVersion.inferFromJar`](https://sourcegraph.com/github.com/sourcegraph/scip-java@main/-/blob/scip-java/src/main/scala/com/sourcegraph/scip_java/buildtools/ScalaVersion.scala?L26:7&subtree=true#tab=references) doesnt consider the full version triplet when provided, so it sees `2.13` and pulls `2.13.6` as defined in [build.sbt](https://sourcegraph.com/github.com/sourcegraph/scip-java/-/blob/build.sbt?L17). So just infer the full version if its in the filename, and otherwise fallback? Well not quite

There must also exist an mtags version for the given full scala version, but there is no `mtags_2.13.10:0.10.6-M1`. For now we could bump both the scala version and the mtags version to match, longer term it may be better to automatically pick an mtags version for a scala version for a reduced maintenance burden at the cost of less determinism.

**Comment by keynmol** [comment]
> I'd expect to be able to execute a goto definition on get, map, and getOrElse, but currently they don't work.

This part seems to be working now (no idea what chaged)? And the scala-library version referenced is 2.13.11, which s

![2023-07-05 10 04 23](https://github.com/sourcegraph/scip-java/assets/1052965/29928f10-674c-47b7-bae8-57bc60fbb513)

**Comment by ckipp01** [comment]
Huh, alright, it seems working so 🚀 . I'll go ahead and close and report back if I hit on this again. Thanks!
