### ISSUE TITLE
Publish Java classes generated from scip.proto as a separate Maven artifact

### ISSUE THREAD

**Issue by yole** [sourcegraph/scip-java#522]
I'm prototyping the integration of scip with IntelliJ IDEA, and right now I'm using a dependency on scip-semanticdb to get access to the scip protobuf-generated classes. This pulls in a bunch of dependencies I don't actually care about. Would it be possible to publish only the protobuf-generated classes as a separate arifact?

**Comment by olafurpg** [comment]
Thank you for reporting! The semanticdb-scip artifact was not intended to be consumed as an external library, which is why it includes unnecessary dependencies. I've opened a PR to publish a separate com.sourcegraph:scip-java artifact, which I'll release as soon as the PR is merged.

https://github.com/sourcegraph/scip-java/pull/523

**Comment by olafurpg** [comment]
The v0.8.9 release is available now on Maven Central.
